name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show environment var
        run: echo ${{ vars.SOME_VAR }}

  test2:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show custom var
        run:
          echo ${{ vars.DB_CONNECTION }}
          echo ${{ vars.DB_HOST }}
          echo ${{ vars.DB_PORT }}
          echo ${{ vars.DB_DATABASE }}
          echo ${{ vars.DB_USERNAME }}
          echo ${{ vars.DB_PASSWORD }}
          echo ${{ vars.DB_CONNECTION }}
          echo ${{ vars.APP_NAME }}
          echo ${{ vars.APP_ENV }}
          echo ${{ vars.APP_KEY }}
          echo ${{ vars.APP_DEBUG }}
          echo ${{ vars.APP_TIMEZONE }}
          echo ${{ vars.APP_URL }}


